config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('main.urls')),
    path('metal/', include('metal.urls')),
    path('stock/', include('stock.urls')),
]

main/urls.py
from django.http import HttpResponse
from django.urls import path

from .views import base_views, sample_views, sample_class_views, error_views


def sample01_func(request):
    return HttpResponse('<h1>sample1_funcに呼ばれました！</h1>')


app_name = 'main'

urlpatterns = [
    path('', base_views.TopView.as_view(), name='index'),
    path('about/', base_views.AbountView.as_view(), name='about'),
    path('reference/', base_views.ReferenceView.as_view(), name='reference'),
    path('buy_thanks/', base_views.ThanksView.as_view(), name='thanks'),

    path('sample01/', sample01_func, name='sample01'),
    path('sample11/', sample_views.SampleClass11(), name='sample11'),
    path('sample12/', sample_views.SampleClass12().my_method, name='sample12'),
    path('sample13/', sample_views.func_13, name='sample13'),
    path('sample21/', sample_class_views.func_21, name='sample21'),
    path('sample22/', sample_class_views.func_22, name='sample22'),
    path('sample23/', sample_class_views.func_23, name='sample23'),

    path('normal_403/', error_views.normal_403, name='normal_403'),
    path('normal_403_class/', error_views.normal_403_class, name='normal_403_class'),
    path('raise_403/', error_views.raise_403, name='raise_403'),

    path('normal_400/', error_views.normal_400, name='normal_400'),
    path('normal_400_class/', error_views.normal_400_class, name='normal_400_class'),
    path('raise_400/', error_views.raise_400, name='raise_400'),

    path('raise_500/', error_views.raise_500, name='raise_500'),
]

metal/urls.py
from django.urls import path

from . import views

app_name = 'metal'
urlpatterns = [
    path('', views.redirect_func, name='redirect'),

    path('index/', views.MetalTopView.as_view(), name='index'),
    path('_index/', views.metal_top_view, name='func_index'),

    path('item/<int:pk>/', views.MetalDetail.as_view(), name='detail'),

    path('buy/', views.MetalBuy.as_view(), name='buy'),
    path('_buy/', views.metal_buy_view, name='func_buy'),

    path('purchase_list/', views.MetalPurchaseList.as_view(), name='purchase_list'),

    path('api/info/', views.MetalAllInfoAPI.as_view(), name='allinfo'),
    path('api/info/buy/', views.metal_buy_api, name='buyapi'),
    path('api/info/<str:type_name>/', views.MetalInfoAPI.as_view(), name='info'),
]

metal/models.py
from django.db import models


# Create your models here.
class Metal(models.Model):
    """
    貴金属の情報

    1gあたりの価格を示す
    """

    name = models.CharField(verbose_name="金属名", max_length=100)
    buy = models.PositiveIntegerField(verbose_name="買値", null=True, blank=True)
    sell = models.PositiveIntegerField(verbose_name='売値', null=True, blank=True)

    def __str__(self):
        return self.name


class MetalPurchase(models.Model):
    """
    貴金属の買取履歴
    """

    metal = models.ForeignKey(Metal, verbose_name="金属名", on_delete=models.PROTECT)
    weight = models.PositiveIntegerField(verbose_name="重量", null=True, blank=True)
    email = models.CharField(verbose_name="email", max_length=255)
    name = models.CharField(verbose_name="取引者", max_length=255)
    created = models.DateTimeField(verbose_name="取引日時", auto_now_add=True)

    def __str__(self):
        return f'{str(self.metal)}_{str(self.created)}'

metal/views.py
import json

from django.contrib import messages
from django.core.exceptions import SuspiciousOperation
from django.http import JsonResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, resolve_url
from django.urls import reverse
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView

from .models import Metal, MetalPurchase


def redirect_func(request):
    """ 関数ベースビューのリダイレクト例 """
    return HttpResponseRedirect(resolve_url('metal:index'))


def metal_top_view(request):
    metals = Metal.objects.all()
    return render(request, 'metal/index.html', context={'metals': metals}, )


def metal_buy_view(request):
    if request.method == 'GET':
        metals = Metal.objects.all()
        context = {"metals": metals}
        return render(request, 'metal/buy.html', context)
    elif request.method == 'POST':
        metal_name = request.POST['metal_name']
        try:
            metal = Metal.objects.get(name=metal_name)
        except Metal.DoesNotExist:
            messages.warning(request, f'Metal type does not exist: {metal_name}')
            return HttpResponseRedirect(reverse('metal:func_buy'))
        weight = request.POST['weight']
        email = request.POST['email']
        name = request.POST['name']

        purchase = MetalPurchase(metal=metal, weight=weight, email=email, name=name)
        purchase.save()

        messages.success(request, '毎度ありがとうございます！')
        return HttpResponseRedirect(reverse('main:thanks'))


# Create your views here.
class MetalTopView(View):
    """トップページ"""

    def get(self, request, *args, **kwargs):
        metals = Metal.objects.all()
        context = {'metals': metals}
        return render(request, 'metal/index.html', context)


class MetalDetail(DetailView):
    """詳細ページ"""

    model = Metal
    template_name = 'metal/detail.html'


class MetalBuy(View):
    """
    貴金属買取ページ
    """

    def get(self, request, *args, **kwargs):
        metals = Metal.objects.all()
        context = {"metals": metals}
        return render(request, 'metal/buy.html', context)

    def post(self, request, *args, **kwargs):
        metal_name = request.POST['metal_name']
        metal = Metal.objects.get(name=metal_name)
        weight = request.POST['weight']
        # if not weight.isnumeric():
        #     messages.warning(request, 'weightは数値にしてね！')
        #     return self.get(request, *args, **kwargs)

        email = request.POST['email']
        name = request.POST['name']

        purchase = MetalPurchase(metal=metal, weight=weight, email=email, name=name)
        purchase.save()

        messages.success(request, '毎度ありがとうございます！')
        return HttpResponseRedirect(reverse('main:thanks'))


# 以下の api views については、 model の設計をいじったあとは動作未確認です。
class MetalInfoAPI(View):
    """
    貴金属の情報を返す
    :param type_name:対象となる金属の名前
    :return:
    """

    def get(self, request, type_name, *args, **kwargs):
        exist = Metal.objects.filter(name=type_name)
        if not exist:
            data = {'error': '受け付けられません。当店では扱っていない貴金属です。'}
            dump_params = {
                "ensure_ascii": False
            }
            return JsonResponse(data, json_dumps_params=dump_params, status=404)
        metal = Metal.objects.get(name=type_name)
        data = {
            'id': metal.id,
            'metal_type': metal.name,
            'buy': metal.buy,
            'sell': metal.sell,
        }
        return JsonResponse(data)


class MetalAllInfoAPI(View):
    """
    全ての貴金属の情報を返す
    """

    def get(self, request, *args, **kwargs):
        metals = Metal.objects.all()
        result_dict = {}
        for metal in metals:
            result_dict[metal.id] = {'id': metal.id, 'metal_type': metal.name, 'buy': metal.buy,
                                     'sell': metal.sell, }

        return JsonResponse(result_dict)


@csrf_exempt
def metal_buy_api(request):
    if request.method == 'GET':
        dump_params = {
            "ensure_ascii": False
        }
        return JsonResponse({'error': 'POSTメソッドのみ受け付けています。'}, json_dumps_params=dump_params, status=404)
    data = json.loads(request.body)
    exist = Metal.objects.filter(metal_type=data['name'])
    if not exist:
        dump_params = {
            "ensure_ascii": False
        }
        data = {'error': '受け付けられません。当店では扱っていない貴金属です。'}
        return JsonResponse(data, json_dumps_params=dump_params, status=404)

    metal = Metal.objects.get(metal_type=data['name'])
    weight = data['amount']
    email = data['email']
    name = data['user']

    purchase = MetalPurchase(metal=metal, weight=weight, email=email, name=name)
    purchase.save()

    data = {
        'result': 'success',
        'price': metal.buy * weight
    }
    return JsonResponse(data)


class MetalPurchaseList(View):
    """
    買取リストを表示する
    """

    def get(self, request, *args, **kwargs):
        purchase_list = MetalPurchase.objects.all().select_related('metal')
        context = {'purchase_list': purchase_list}
        return render(request, 'metal/purchase_list.html', context)

# class MetalBuyAPI(View):
#     """
#     貴金属買取API
#     """
#
#     def get(self, request, *args, **kwargs):
#         dump_params = {
#             "ensure_ascii": False
#         }
#         return JsonResponse({'error': 'POSTメソッドのみ受け付けています。'}, json_dumps_params=dump_params, status=404)
#
#     @method_decorator(ensure_csrf_cookie)
#     def post(self, request, *args, **kwargs):
#         metal_type = request.POST['metal_type']
#         exist = Metal.objects.filter(metal_type=metal_type)
#         if not exist:
#             dump_params = {
#                 "ensure_ascii": False
#             }
#             data = {'error': '受け付けられません。当店では扱っていない貴金属です。'}
#             return JsonResponse(data, json_dumps_params=dump_params, status=404)
#
#         metal_type = Metal.objects.get(metal_type=metal_type)
#         weight = request.POST['weight']
#         email = request.POST['email']
#         name = request.POST['name']
#
#         purchase = MetalPurchase(metal_type=metal_type, weight=weight, email=email, name=name)
#         purchase.save()
#
#         data = {
#             'result': 'success',
#             'price': metal_type.buy * weight
#         }
#         return JsonResponse(data)

templates/metal/buy.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'favicon-gold.ico' %}">
    <style>
        form div.field {
            display: flex;
        }

        label {
            width: 200px;
        }
    </style>
    <title>Django貴金属の買取ページへようこそ！</title>
</head>
<body>
<h1>Django貴金属の買取ページです</h1>
<section class="section">
    貴金属を買い取ります。<br>
    売りたい貴金属の情報を、以下のフォームに入力してください。<br>
    <br>
    <div class="form">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="field">
                <label for="metal_type">金属:</label>
                {% for metal in metals %}
                    <input type="radio" name="metal_name" id="{{ metal.name }}" value="{{ metal.name }}">{{ metal.name }}
                {% endfor %}
            </div>
            <div class="field">
                <label for="weight">重さ：</label>
                <input type="text" name="weight">
            </div>
            <div class="field">
                <label for="email">連絡先メールアドレス：</label>
                <input type="text" name="email" required>
            </div>
            <div class="field">
                <label for="name">お名前：</label>
                <input type="text" name="name" required>
            </div>
            <input type="submit" value="送信する">
        </form>
    </div>
    <p>
        <a href="{% url 'metal:index' %}">Django貴金属トップに戻る</a><br>
        <a href="{% url 'main:index' %}">トップに戻る</a><br>
    </p>
</section>
</body>
</html>

templates/metal/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'favicon-gold.ico' %}">
    <style>
        ul {
            list-style: none;
        }

        .ul-flex {
            display: flex;
        }

        .metal_type {
            width: 100px;
            text-align: center;
            margin-right: 10px
        }

        .buy {
            width: 100px;
            text-align: center;
        }

        .sell {
            width: 100px;
            text-align: center;
        }

        .detail {
            width: 200px;
            text-align: center;
        }

        .label {
            text-align: center;
        }

        p.links {
            border-top: 1px solid black;
            padding-top: 30px;
            margin-top: 30px;
        }
    </style>
    <title>Django貴金属へようこそ</title>
</head>
<body>
<h1>Django貴金属へようこそ！</h1>
<section class="section">
    貴金属を高値で買い取ります。<br>
    貴金属を最安値で販売します。<br>
    <br>
    本日の買取/販売価格は以下の通りです。(1グラムあたり単価)<br>
    <ul>
        <li id="title">
            <ul class="ul-flex">
                <li class="metal_type label">金属</li>
                <li class="buy label">買い取り</li>
                <li class="sell label">販売</li>
                <li class="detail label">詳細ページへのリンク</li>
            </ul>
        </li>
        <li id="{{ metal.metal_name }}">
            <ul class="ul-flex">
                <li class="metal_type">{{ metal.name }}</li>
                <li class="buy">{{ metal.buy }}</li>
                <li class="sell">{{ metal.sell }}</li>
                <li class="detail"><a href="{% url 'metal:detail' pk=metal.pk %}">リンク</a></li>
            </ul>
        </li>
    </ul>
    <p class="links">
        <a href="{% url 'metal:buy' %}">貴金属を売る</a><br>
        <a href="{% url 'metal:purchase_list' %}">貴金属売買履歴</a><br>
        <a href="#">貴金属を買う(販売は休止しています)</a><br>
        <a href="{% url 'main:index' %}">トップに戻る</a><br>
    </p>

</section>

</body>
</html>

templates/metal/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'favicon-gold.ico' %}">
    <style>
        ul {
            list-style: none;
        }

        .ul-flex {
            display: flex;
        }

        .metal_type {
            width: 100px;
            text-align: center;
            margin-right: 10px
        }

        .buy {
            width: 100px;
            text-align: center;
        }

        .sell {
            width: 100px;
            text-align: center;
        }

        .detail {
            width: 200px;
            text-align: center;
        }

        .label {
            text-align: center;
        }

        p.links {
            border-top: 1px solid black;
            padding-top: 30px;
            margin-top: 30px;
        }
    </style>
    <title>Django貴金属へようこそ</title>
</head>
<body>
<h1>Django貴金属へようこそ！</h1>
<section class="section">
    貴金属を高値で買い取ります。<br>
    貴金属を最安値で販売します。<br>
    <br>
    本日の買取/販売価格は以下の通りです。(1グラムあたり単価)<br>
    <ul>
        <li id="title">
            <ul class="ul-flex">
                <li class="metal_type label">金属</li>
                <li class="buy label">買い取り</li>
                <li class="sell label">販売</li>
                <li class="detail label">詳細ページへのリンク</li>
            </ul>
        </li>
        {% for metal in metals %}
            <li id="{{ metal.metal_name }}">
                <ul class="ul-flex">
                    <li class="metal_type">{{ metal.name }}</li>
                    <li class="buy">{{ metal.buy }}</li>
                    <li class="sell">{{ metal.sell }}</li>
                    <li class="detail"><a href="{% url 'metal:detail' pk=metal.pk %}">リンク</a></li>
                </ul>
            </li>
        {% endfor %}
    </ul>
    <p class="links">
        <a href="{% url 'metal:buy' %}">貴金属を売る</a><br>
        <a href="{% url 'metal:purchase_list' %}">貴金属売買履歴</a><br>
        <a href="#">貴金属を買う(販売は休止しています)</a><br>
        <a href="{% url 'main:index' %}">トップに戻る</a><br>
    </p>

</section>

</body>
</html>

templates/metal/purchase_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'favicon-gold.ico' %}">
    <style>
        ul {
            list-style: none;
        }

        .ul-flex {
            display: grid;
            grid-template-columns: 30px 90px 75px 75px 300px 125px 175px;
        }

        .metal_type {
            width: 100px;
            text-align: right;
            margin-right: 10px
        }

        .buy {
            width:100px;
            text-align:right;
        }
        .sell {
            width: 100px;
            text-align: right;
        }

        .label {
            text-align :center;
        }

    </style>
    <title>Django貴金属の取引記録</title>
</head>
<body>
<h1>Django貴金属の取引記録ページです</h1>
<section class="section">
    本来は、管理者しか見れないページですが、今回は、誰でも見れるようにしています。<br>
    <ul>
        <li id="title">
            <ul class="ul-flex">
                <li class="purchase-id">id</li>
                <li class="purchase-metal">金属</li>
                <li class="purchase-total-price">単価</li>
                <li class="purchase-weight">重量</li>
                <li class="purchase-email">email</li>
                <li class="purchase-name">name</li>
                <li class="purchase-created">created</li>
            </ul>
        </li>
        {% for purchase in purchase_list %}
            <li id="{{ purchase.id }}">
                <ul class="ul-flex">
                    <li class="purchase-id">{{ purchase.id }}</li>
                    <li class="purchase-id">{{ purchase.metal.name }}</li>
                    <li class="purchase-id">{{ purchase.metal.buy }}</li>
                    <li class="purchase-weight">{{ purchase.weight }}</li>
                    <li class="purchase-email">{{ purchase.email }}</li>
                    <li class="purchase-name">{{ purchase.name }}</li>
                    <li class="purchase-created">{{ purchase.created|date:'Y/m/d H:i' }}</li>
                </ul>
            </li>
        {% endfor %}
    </ul>
    <p>
        <a href="{% url 'metal:buy' %}">貴金属を売る</a><br>
        <a href="#">貴金属を買う(販売は休止しています)</a><br>
        <a href="{% url 'main:index' %}">トップに戻る</a><br>
    </p>

</section>

</body>
</html>