config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('main.urls')),
    path('metal/', include('metal.urls')),
    path('stock/', include('stock.urls')),
]

main/urls.py
from django.http import HttpResponse
from django.urls import path

from .views import base_views, sample_views, sample_class_views, error_views


def sample01_func(request):
    return HttpResponse('<h1>sample1_funcに呼ばれました！</h1>')


app_name = 'main'

urlpatterns = [
    path('', base_views.TopView.as_view(), name='index'),
    path('about/', base_views.AbountView.as_view(), name='about'),
    path('reference/', base_views.ReferenceView.as_view(), name='reference'),
    path('buy_thanks/', base_views.ThanksView.as_view(), name='thanks'),

    path('sample01/', sample01_func, name='sample01'),
    path('sample11/', sample_views.SampleClass11(), name='sample11'),
    path('sample12/', sample_views.SampleClass12().my_method, name='sample12'),
    path('sample13/', sample_views.func_13, name='sample13'),
    path('sample21/', sample_class_views.func_21, name='sample21'),
    path('sample22/', sample_class_views.func_22, name='sample22'),
    path('sample23/', sample_class_views.func_23, name='sample23'),

    path('normal_403/', error_views.normal_403, name='normal_403'),
    path('normal_403_class/', error_views.normal_403_class, name='normal_403_class'),
    path('raise_403/', error_views.raise_403, name='raise_403'),

    path('normal_400/', error_views.normal_400, name='normal_400'),
    path('normal_400_class/', error_views.normal_400_class, name='normal_400_class'),
    path('raise_400/', error_views.raise_400, name='raise_400'),

    path('raise_500/', error_views.raise_500, name='raise_500'),
]

metal/urls.py
from django.urls import path

from . import views

app_name = 'metal'
urlpatterns = [
    path('', views.redirect_func, name='redirect'),

    path('index/', views.MetalTopView.as_view(), name='index'),
    path('_index/', views.metal_top_view, name='func_index'),

    path('item/<int:pk>/', views.MetalDetail.as_view(), name='detail'),

    path('buy/', views.MetalBuy.as_view(), name='buy'),
    path('_buy/', views.metal_buy_view, name='func_buy'),

    path('purchase_list/', views.MetalPurchaseList.as_view(), name='purchase_list'),

    path('api/info/', views.MetalAllInfoAPI.as_view(), name='allinfo'),
    path('api/info/buy/', views.metal_buy_api, name='buyapi'),
    path('api/info/<str:type_name>/', views.MetalInfoAPI.as_view(), name='info'),
]

stock/urls.py
from django.urls import path
from . import views

app_name = 'stock'
urlpatterns = [
    path('', views.RedirectToIndex.as_view(), name='redirect'),
    path('index/', views.StockTopView.as_view(), name='index'),
    path('item/<int:pk>/', views.stock_detail, name='detail'),
    path('buy/', views.StockBuy.as_view(), name='buy'),
    path('_buy/', views.stock_buy, name='buy_func'),
    path('purchase_list/', views.StockPurchaseList.as_view(), name='purchase_list'),
]

templates/_400.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>このページは利用できません</h1>
<p>400だよ！</p>
<p>リクエストの内容がいまいち不審...なので、マトモにお返事しません。</p>
<p><a href="/">トップページに戻る</a></p></body>
</html>

templates/_403.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>このページは利用できません</h1>
<p>403だよ！</p>
<p>あなたが来てはいけないということになっているページです。</p>
<p><a href="/">トップページに戻る</a></p></body>
</html>

templates/_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>このページは利用できません</h1>
<p>404だよ！</p>
<p>アクセスできないURLか、ページが削除されています。</p>
<p><a href="/">トップページに戻る</a></p></body>
</html>

templates/_500.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>このページは利用できません</h1>
<p>500だよ！</p>
<p>サーバ側で致命的なエラーが生じました。ごめんなさい。</p>
<p><a href="/">トップページに戻る</a></p></body>
</html>

templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="{% static 'favicon-gold.ico' %}">
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
    <title>Django貴金属/Django証券の合同サイトについて</title>
</head>
<body>
<section class="section" id="main">
    <h1>Django貴金属/Django証券の合同サイトについて</h1>
    <p class="message">
        このページは、HTMLページの基本構成やリクエスト/レスポンスについての解説のために作ったダミーページです
    </p>
    <p>
        <span class="red-large normal">実在する企業のWEBサイトではありません</span><br>
        <span class="red-large bold bg-yellow">貴金属/証券ほか、いかなる金融資産についての取引もできません</span>
    </p>
</section>
<footer>
    <ul>
        <li><a href="{% url 'main:index' %}">トップに戻る</a></li>
        <li><a href="{% url 'main:about' %}">はじめての方へ</a></li>
        <li><a href="{% url 'main:reference' %}">リファレンス</a></li>
        <li><a href="#" target="_blank">運営者</a></li>
        <li><a href="#" target="_blank">お問い合わせ</a></li>
    </ul>
</footer>
</body>
</html>

templates/buy_thanks.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'favicon-gold.ico' %}">
    <title>お取引ありがとうございます。</title>
    <style>
        section.message-area > div.message.success {
            background-color: green;
            color: white;
        }
    </style>
</head>
<body>
{% if messages %}
    <section class="message-area">
        {% for message in messages %}
            <div class="message {% if message.tags %}{{ message.tags }}{% endif %}">
                <p class="message-text">{{ message }}</p>
            </div>
        {% endfor %}
    </section>
{% endif %}
<section class="section">
    お取引ありがとうございます。<br>
    今後とも、ガラパゴス貴金属をよろしくお願いいたします。<br>
</section>
<div>
    <ul>
        <li><a href="{% url 'main:index' %}">トップに戻る</a></li>
        <li><a href="{% url 'main:about' %}">はじめての方へ</a></li>
        <li><a href="{% url 'main:reference' %}">リファレンス</a></li>
        <li><a href="#" target="_blank">運営者紹介</a></li>
        <li><a href="#" target="_blank">お問い合わせ</a></li>
    </ul>
</div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'favicon-gold.ico' %}">
    <style>
        footer {
            border-top: 20px;
            border-top: solid 1px #e6e6e6;
        }

        #main {
            background-color: mediumseagreen;
            padding: 20px;
        }

        div#company-link-area {
            background-color: mediumturquoise;
            border: darkblue 1px solid;
            margin: 20px;
            padding: 20px;
        }

        a.company-link:hover {
            color: crimson;
            background-color: gold;
        }

        #view-basic-samples ul li ul {
            display: flex;
            margin-bottom: 30px;
        }

        #view-basic-samples ul li {
            margin-left: 20px;
            margin-right: 20px;
        }

        footer ul {
            display: flex;
        }

        footer ul li {
            margin-left: 20px;
            margin-right: 20px;
        }

    </style>
    <title>Django貴金属/Django証券の合同サイト</title>
</head>
<body>
<section class="section" id="main">
    <!--  ヘッダーとリンク  -->
    <h1>Django貴金属/Django証券の合同サイトへようこそ！</h1>
    <div id="company-link-area">
        <p>このドメインでは、以下の会社がウェブサイトを運営しています</p>
        <div class="company-info">
            <a href="{% url 'metal:redirect' %}" id="django-metal" class="company-link metal">
                Django貴金属株式会社
            </a><br>
        </div>
        <div class="company-info">
            <a href="{% url 'stock:redirect' %}" id="django-stock" class="company-link stock">
                Django証券株式会社
            </a>
        </div>
    </div>
</section>
<section class="section" id="view-basic-samples">
    <ul>
        <li>
            <span>正常系のサンプル</span>
            <ul>
                <li><a href="{% url 'main:sample01' %}">sample01</a></li>
                <li><a href="{% url 'main:sample11' %}">sample11</a></li>
                <li><a href="{% url 'main:sample12' %}">sample12</a></li>
                <li><a href="{% url 'main:sample13' %}">sample13</a></li>
                <li><a href="{% url 'main:sample21' %}">sample21</a></li>
                <li><a href="{% url 'main:sample22' %}">sample22</a></li>
                <li><a href="{% url 'main:sample23' %}">sample23</a></li>
            </ul>
        </li>
        <li>
            <span>404エラーのサンプル(not found)</span>
            <ul>
                <li><a href="/hoge/fuga/">404(通常)</a></li>
                <li><a href="{% url 'stock:detail' pk=100 %}">404(raise)</a></li>
                <li><a href="{% url 'metal:detail' pk=100 %}">404(get_object_or_404)</a></li>
            </ul>
        </li>
        <li>
            <span>403エラーのサンプル(forbidden)</span>
            <ul>
                <li><a href="{% url 'main:normal_403' %}">403(通常)</a></li>
                <li><a href="{% url 'main:normal_403_class' %}">403(HttpResponseForbidden)</a></li>
                <li><a href="{% url 'main:raise_403' %}">403(raise)</a></li>
            </ul>
        </li>
        <li>
            <span>400エラーのサンプル(bad request)</span>
            <ul>
                <li><a href="{% url 'main:normal_400' %}">400(ステータスコード指定)</a></li>
                <li><a href="{% url 'main:normal_400_class' %}">400(BadRequest)</a></li>
                <li><a href="{% url 'main:raise_400' %}">400(raise)</a></li>
            </ul>
        </li>
        <li>
            <span>500エラーのサンプル(internal server error)</span>
            <ul>
                <li><a href="{% url 'main:raise_500' %}">500(raise)</a></li>
            </ul>
        </li>
    </ul>
</section>
<footer class="footer-area">
    <ul>
        <li><a href="{% url 'main:about' %}">初めての方へ</a></li>
        <li><a href="{% url 'main:reference' %}">リファレンス</a></li>
        <li><a href="#" target="_blank">運営者紹介</a></li>
        <li><a href="#" target="_blank">お問い合わせ</a></li>
    </ul>
</footer>
</body>
</html>

templates/reference.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/combine/npm/github-markdown-css@5.1.0,npm/github-markdown-css@5.1.0/github-markdown-light.min.css">
    <title>ガラパゴス貴金属/ガラパゴス証券のURLリファレンス</title>
</head>
<body>
<section class="section" id="main">
    <h1>ガラパゴス貴金属/ガラパゴス証券のURLリファレンス</h1>
    <p class="message">
        このページは、HTMLページのURLリファレンスです。<br>
    </p>
    <div class="markdown-body">
        {{ note | safe }}
    </div>
</section>
<footer>
    <ul>
        <li><a href="/">トップに戻る</a></li>
        <li><a href="/about/">はじめての方へ</a></li>
        <li><a href="/reference/">リファレンス</a></li>
        <li><a href="https://forum.pc5bai.com/company/" target="_blank">運営者紹介</a></li>
        <li><a href="https://forum.pc5bai.com/toiawase/create/" target="_blank">お問い合わせ</a></li>
    </ul>
</footer>
</body>
</html>

templates/sample_with_context.html
<h1>SampleClass23に呼ばれました！</h1>

<p>{{ message }}</p>

templates/sample_without_context.html
<h1>SampleClass22に呼ばれました！</h1>