config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('main.urls')),
    path('metal/', include('metal.urls')),
    path('stock/', include('stock.urls')),
]

main/urls.py
from django.http import HttpResponse
from django.urls import path

from .views import base_views, sample_views, sample_class_views, error_views


def sample01_func(request):
    return HttpResponse('<h1>sample1_funcに呼ばれました！</h1>')


app_name = 'main'

urlpatterns = [
    path('', base_views.TopView.as_view(), name='index'),
    path('about/', base_views.AbountView.as_view(), name='about'),
    path('reference/', base_views.ReferenceView.as_view(), name='reference'),
    path('buy_thanks/', base_views.ThanksView.as_view(), name='thanks'),

    path('sample01/', sample01_func, name='sample01'),
    path('sample11/', sample_views.SampleClass11(), name='sample11'),
    path('sample12/', sample_views.SampleClass12().my_method, name='sample12'),
    path('sample13/', sample_views.func_13, name='sample13'),
    path('sample21/', sample_class_views.func_21, name='sample21'),
    path('sample22/', sample_class_views.func_22, name='sample22'),
    path('sample23/', sample_class_views.func_23, name='sample23'),

    path('normal_403/', error_views.normal_403, name='normal_403'),
    path('normal_403_class/', error_views.normal_403_class, name='normal_403_class'),
    path('raise_403/', error_views.raise_403, name='raise_403'),

    path('normal_400/', error_views.normal_400, name='normal_400'),
    path('normal_400_class/', error_views.normal_400_class, name='normal_400_class'),
    path('raise_400/', error_views.raise_400, name='raise_400'),

    path('raise_500/', error_views.raise_500, name='raise_500'),
]

stock/urls.py
from django.urls import path
from . import views

app_name = 'stock'
urlpatterns = [
    path('', views.RedirectToIndex.as_view(), name='redirect'),
    path('index/', views.StockTopView.as_view(), name='index'),
    path('item/<int:pk>/', views.stock_detail, name='detail'),
    path('buy/', views.StockBuy.as_view(), name='buy'),
    path('_buy/', views.stock_buy, name='buy_func'),
    path('purchase_list/', views.StockPurchaseList.as_view(), name='purchase_list'),
]

stock/models.py
from django.db import models
from django.utils import timezone


class Stock(models.Model):
    """
    株価の情報
    """

    name = models.CharField(verbose_name="銘柄名", max_length=100)
    buy = models.PositiveIntegerField(verbose_name="買値", null=True, blank=True)
    sell = models.PositiveIntegerField(verbose_name='売値', null=True, blank=True)

    def __str__(self):
        return self.name


class StockPurchase(models.Model):
    """
    株の買取履歴
    """

    stock = models.ForeignKey(Stock, verbose_name="銘柄名", on_delete=models.PROTECT)
    weight = models.PositiveIntegerField(verbose_name="株数", )
    email = models.EmailField(verbose_name="連絡先メールアドレス", max_length=255)
    name = models.CharField(verbose_name="お名前", max_length=255)
    created = models.DateTimeField(verbose_name="取引日時", default=timezone.now)

    def __str__(self):
        return f'{str(self.stock)}_{str(self.created)}'

stock/forms.py
from django import forms

from stock.models import StockPurchase


class StockPurchaseForm(forms.ModelForm):
    class Meta:
        model = StockPurchase
        fields = ['stock', 'weight', 'email', 'name', ]
        widgets = {
            'weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'stock': forms.RadioSelect(attrs={'class': 'form-check-input'}),
        }

stock/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import resolve_url, render, redirect
from django.views import View
from django.views.generic import ListView, CreateView, RedirectView

from stock.forms import StockPurchaseForm
from stock.models import Stock, StockPurchase


class StockPurchaseList(View):
    """
    買取リストを表示する
    """

    def get(self, request, *args, **kwargs):
        purchase_list = StockPurchase.objects.all().select_related('stock')
        context = {'purchase_list': purchase_list}
        return render(request, 'stock/purchase_list.html', context)


class StockTopView(ListView):
    model = Stock
    template_name = 'stock/index.html'


def stock_detail(request, pk):
    """
    商品の詳細ページ

    Stock クラスのインスタンスを取得し、その詳細情報を返す
    """
    try:
        stock = Stock.objects.get(pk=pk)
    except Stock.DoesNotExist:
        raise Http404('Stock does not exist')
    # stock = get_object_or_404(Stock, pk=pk)
    return render(request, 'stock/detail.html', {'stock': stock})


def stock_buy(request):
    if request.method == 'POST':
        form = StockPurchaseForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, '毎度ありがとうございます！')
            return redirect('main:thanks')
        else:
            for key, value in form.errors.items():
                messages.warning(request, f'{key}:{value[0]}')
    else:
        form = StockPurchaseForm()
    return render(request, 'stock/buy.html', {'form': form})


class StockBuy(CreateView):
    form_class = StockPurchaseForm
    template_name = 'stock/buy.html'

    def form_invalid(self, form):
        for key, value in form.errors.items():
            messages.warning(self.request, f'{key}:{value[0]}')
        return super().form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, '毎度ありがとうございます！')
        return super().form_valid(form)

    def get_success_url(self):
        return resolve_url('main:thanks')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stocks'] = Stock.objects.all()
        return context


class RedirectToIndex(RedirectView):
    """ クラスベースビューのリダイレクト例 """

    def get_redirect_url(self, *args, **kwargs):
        return resolve_url('stock:index')

templates/stock/buy.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        form p {
            display: flex;
        }

        #id_stock_price div {
            display: inline;
        }

        label {
            width: 200px;
        }

        section.message-area > div.message.warning {
            background-color: red;
            color: white;
        }
    </style>
    <title>ガラパゴス証券の買い取りページへようこそ！</title>
</head>
<body>
<h1>ガラパゴス証券の買い取りページです</h1>
{% if messages %}
    <section class="message-area">
        {% for message in messages %}
            <div class="message {% if message.tags %}{{ message.tags }}{% endif %}">
                <p class="message-text">{{ message }}</p>
            </div>
        {% endfor %}
    </section>
{% endif %}
<section class="section">
    証券を買い取ります。<br>
    売りたい証券の情報を、以下のフォームに入力してください。<br>
    <br>
    <div class="form">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="送信する">
        </form>
    </div>
    <p>
        <a href="/stock/">ガラパゴス証券トップに戻る</a><br>
        <a href="/">トップに戻る</a><br/>
    </p>
</section>
</body>
</html>

templates/stock/detail.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        ul {
            list-style: none;
        }

        .ul-flex {
            display: flex;
        }

        .company_name {
            width: 100px;
            text-align: right;
            margin-right: 10px;
        }

        .buy {
            width: 100px;
            text-align: center;
        }

        .sell {
            width: 100px;
            text-align: center;
        }

        .detail {
            width: 200px;
            text-align: center;
        }

        .label {
            text-align: center;
        }

        p.links {
            border-top: 1px solid black;
            padding-top: 30px;
            margin-top: 30px;
        }
    </style>
    <title>ガラパゴス証券で売買できる「{{ stock.name }}」株の紹介です！</title>
</head>
<body>
<h1>ガラパゴス証券で売買できる「{{ stock.name }}」株の紹介です！</h1>
<section class="section">
    株券を高値で買い取ります。<br>
    株券を安値で販売します。<br>
    <br>
    只今の買取/販売価格は以下のとおりです。(1株あたり単価)<br>
    <ul>
        <li id="title">
            <ul class="ul-flex">
                <li class="company_name label">会社コード:</li>
                <li class="buy label">買い取り</li>
                <li class="sell label">販売</li>
                <li class="detail label">詳細ページへのリンク</li>
            </ul>
        </li>
        <li id="{{ stock.name }}">
            <ul class="ul-flex">
                <li class="company_name">{{ stock.name }}:</li>
                <li class="buy">{{ stock.buy }}円</li>
                <li class="sell">{{ stock.sell }}円</li>
                <li class="detail"><a href="{% url 'stock:detail' pk=stock.pk %}">リンク</a></li>
            </ul>
        </li>
    </ul>
    <p class="links">
        <a href="/stock/buy/">株券を売る</a><br>
        <a href="#">株券を買う(販売は休止しています)</a><br>
        <a href="/">トップに戻る</a><br/>
    </p>
</section>
</body>
</html>

templates/stock/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        ul {
            list-style: none;
        }

        .ul-flex {
            display: flex;
        }

        .company_name {
            width: 100px;
            text-align: right;
            margin-right: 10px;
        }

        .buy {
            width: 100px;
            text-align: center;
        }

        .sell {
            width: 100px;
            text-align: center;
        }

        .detail {
            width: 200px;
            text-align: center;
        }

        .label {
            text-align: center;
        }

        p.links {
            border-top: 1px solid black;
            padding-top: 30px;
            margin-top: 30px;
        }
    </style>
    <title>ガラパゴス証券へようこそ！</title>
</head>
<body>
<h1>ガラパコス証券へようこそ！</h1>
<section class="section">
    株券を高値で買い取ります。<br>
    株券を安値で販売します。<br>
    <br>
    只今の買取/販売価格は以下のとおりです。(1株あたり単価)<br>
    <ul>
        <li id="title">
            <ul class="ul-flex">
                <li class="company_name label">会社コード:</li>
                <li class="buy label">買い取り</li>
                <li class="sell label">販売</li>
                <li class="detail label">詳細ページへのリンク</li>
            </ul>
        </li>
        {% for object in object_list %}
            <li id="{{ object.name }}">
                <ul class="ul-flex">
                    <li class="company_name">{{ object.name }}:</li>
                    <li class="buy">{{ object.buy }}円</li>
                    <li class="sell">{{ object.sell }}円</li>
                    <li class="detail"><a href="{% url 'stock:detail' pk=object.pk %}">リンク</a></li>
                </ul>
            </li>
        {% endfor %}
    </ul>
    <p class="links">
        <a href="/stock/buy/">株券を売る</a><br>
        <a href="/stock/purchase_list/">株券購入履歴</a><br>
        <a href="#">株券を買う(販売は休止しています)</a><br>
        <a href="/">トップに戻る</a><br/>
    </p>
</section>
</body>
</html>

templates/stock/purchase_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'favicon-gold.ico' %}">
    <style>
        ul {
            list-style: none;
        }

        .ul-flex {
            display: grid;
            grid-template-columns: 30px 90px 75px 75px 300px 125px 175px;
        }

        .stock_type {
            width: 100px;
            text-align: right;
            margin-right: 10px
        }

        .buy {
            width:100px;
            text-align:right;
        }
        .sell {
            width: 100px;
            text-align: right;
        }

        .label {
            text-align :center;
        }

    </style>
    <title>Django証券の取引記録</title>
</head>
<body>
<h1>Django証券の取引記録ページです</h1>
<section class="section">
    本来は、管理者しか見れないページですが、今回は、誰でも見れるようにしています。<br>
    <ul>
        <li id="title">
            <ul class="ul-flex">
                <li class="purchase-id">id</li>
                <li class="purchase-stock">証券</li>
                <li class="purchase-total-price">単価</li>
                <li class="purchase-weight">株数</li>
                <li class="purchase-email">email</li>
                <li class="purchase-name">name</li>
                <li class="purchase-created">created</li>
            </ul>
        </li>
        {% for purchase in purchase_list %}
            <li id="{{ purchase.id }}">
                <ul class="ul-flex">
                    <li class="purchase-id">{{ purchase.id }}</li>
                    <li class="purchase-name">{{ purchase.stock.name }}</li>
                    <li class="purchase-buy">{{ purchase.stock.buy }}</li>
                    <li class="purchase-weight">{{ purchase.weight }}</li>
                    <li class="purchase-email">{{ purchase.email }}</li>
                    <li class="purchase-name">{{ purchase.name }}</li>
                    <li class="purchase-created">{{ purchase.created|date:'Y/m/d H:i' }}</li>
                </ul>
            </li>
        {% endfor %}
    </ul>
    <p>
        <a href="{% url 'stock:buy' %}">株券を売る</a><br>
        <a href="#">株券を買う(販売は休止しています)</a><br>
        <a href="{% url 'main:index' %}">トップに戻る</a><br>
    </p>

</section>

</body>
</html>